# Generated by Django 2.2.10 on 2021-04-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210418_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Poll created datetime'),
        ),
    ]
