# Generated by Django 2.2.10 on 2021-04-18 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210418_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='finished',
        ),
        migrations.AddField(
            model_name='poll',
            name='finish_date',
            field=models.DateField(default=datetime.date(2021, 4, 18), verbose_name='Poll finish date'),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 4, 18), verbose_name='Poll start date'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Poll created datetime'),
        ),
    ]
