# Generated by Django 2.2.10 on 2021-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210418_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='finish_date',
            field=models.DateField(verbose_name='Poll finish date'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(verbose_name='Poll start date'),
        ),
    ]
